// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/BarChart/barChart.vue')['default']
    Container: typeof import('./components/Container/index.vue')['default']
    PieChart: typeof import('./components/PieChart/pieChart.vue')['default']
  }
}

export {}
